### ISSUE TITLE
Need to be able to enable/disable item colliders in esc scripts

### ISSUE THREAD

**Issue by anneomcl** [punto-/mystery2#3]
Since the player will walk around and press buttons to examine things, rather than point and click, we will have static colliders and colliders to detect the interaction. These will need to be disabled.

The colliders will also need to be turned off BEFORE the player says the dialogue. Let's say I find an item and press "space". I say "Great! It's money!", then press "space" to make the speech go away. This triggers the collider again. Then the collider is removed and the dialogue goes away and we're back in the expected state.

So either the "set_active" is modified or extended to accommodate this behavior, OR a new command is made.

**Comment by punto-** [comment]
set_active hides the whole scene, so the collider should get disabled.. but
this should be fixed by disabling interactions while an esc event is running

**Comment by anneomcl** [comment]
This is now fixed in my branch!
