### ISSUE TITLE
Area2D collision detection should be streamlined

### ISSUE THREAD

**Issue by anneomcl** [punto-/mystery2#5]
When player presses "use", check if player overlaps with any Area2D colliders to trigger an interaction. If not, do nothing.

Right now every single "Interactable" Node is initialized to connect enter() and exit() functions, which isn't necessary.

**Comment by anneomcl** [comment]
I think it makes sense for a "check_collisions()" function to exist in the player.gd script. Where for each input event, we check for a collision with an Area2D, and trigger an interaction if it satisfies the requirements.

However, we'd need to store a list of Area2D colliders for easy access to use "get_all_bodies" or check if player "is_overlapping_body" on each one. We could keep my manual "Interactable" group that I use to initialize them. 

Considering leaving things as they are but moving the on_Area2D_enter/exit functions outside of the player script.

Still thinking about this design though...

**Comment by punto-** [comment]
I don't think it's necessary to store a list, when you have a body on the
overlapping bodies list you can check if it's an object by getting its
parent (assuming the area is direct child of the root of the item), and
checking if it inherits from intearctive.gd, which has the "interact()"
method. Something like this:

if body.get_parent() extends preload("res://globals/interactive.gd"):
   body.get_parent().interact()

**Comment by anneomcl** [comment]
Looks like you fixed this in most recent commit by adding Area2D to player!

**Comment by punto-** [comment]
Yeah.. I'm not 100% happy with this solution, I think each item could
notify the "game" class when the player enters or exits its area, then the
game could do things like show icons in the current target for interaction,
etc. But for now this works..
